name: 02 - Workflow Events

on:
  push:
  schedule:
    - cron: '0 17 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Show the Trigger"
