name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install tree
        run: sudo apt-get install -y tree  

      - name: Printing Folders
        run: |
          echo "Printing folder structure"
          tree
          

